# Generated by Django 2.0.3 on 2018-04-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
