# Generated by Django 2.0.3 on 2018-04-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_picture_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.TextField(),
        ),
    ]
